-- Aplicar este script desde el usuario system o sys
-- Crear usuario GMLSOFTWARE
CREATE USER GMLSOFTWARE IDENTIFIED BY GMLSOFTWARE
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

-- Otorgar permisos necesarios al usuario GMLSOFTWARE
GRANT CONNECT, RESOURCE TO GMLSOFTWARE;
GRANT CREATE SESSION TO GMLSOFTWARE;
GRANT CREATE SEQUENCE TO GMLSOFTWARE;
GRANT CREATE TABLE TO GMLSOFTWARE;
GRANT CREATE VIEW TO GMLSOFTWARE;
GRANT DBA TO GMLSOFTWARE;

CONNECT GMLSOFTWARE/GMLSOFTWARE;

CREATE TABLE CLIENTES (
    CLIENTE_ID NUMBER PRIMARY KEY,
    PRIMER_NOMBRE VARCHAR2(50) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR2(50),
    PRIMER_APELLIDO VARCHAR2(50) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(50) NOT NULL,
    CLAVE_COMPARTIDA VARCHAR2(51) NOT NULL,
    CORREO_ELECTRONICO VARCHAR2(100) UNIQUE NOT NULL,
    TELEFONO VARCHAR2(20),
    FECHA_INICIO TIMESTAMP,
    FECHA_FIN TIMESTAMP,
    FECHA_CREACION TIMESTAMP NOT NULL,
    FECHA_MODIFICACION TIMESTAMP
);

CREATE SEQUENCE sec_clientes START WITH 1 INCREMENT BY 1;
